Left Stick Left: LX-
Left Stick Down: LY+
Left Stick Right: LX+
Left Stick Up: LY-
Right Stick Left: RX-
Right Stick Down: RY+
Right Stick Right: RX+
Right Stick Up: RY-
Start: TR
Select: TL
PS Button: Mode
Square: C
Cross: A
Circle: B
Triangle: X
Left: Hat0 X-
Down: Hat0 Y+
Right: Hat0 X+
Up: Hat0 Y-
R1: Z
R2: RZ+
R3: TR 2
L1: Y
L2: LZ+
L3: TL 2
Left Stick Multiplier: 100
Right Stick Multiplier: 100
Left Stick Deadzone: 30
Right Stick Deadzone: 30
Left Trigger Threshold: 0
Right Trigger Threshold: 0
Left Pad Squircling Factor: 5000
Right Pad Squircling Factor: 5000
Color Value R: 0
Color Value G: 0
Color Value B: 0
Blink LED when battery is below 20%: true
Use LED as a battery indicator: false
LED battery indicator brightness: 50
Enable Large Vibration Motor: true
Enable Small Vibration Motor: true
Switch Vibration Motors: false
Mouse Deadzone X Axis: 60
Mouse Deadzone Y Axis: 60
Mouse Acceleration X Axis: 200
Mouse Acceleration Y Axis: 250
Left Stick Lerp Factor: 100
Right Stick Lerp Factor: 100
Analog Button Lerp Factor: 100
Trigger Lerp Factor: 100
Device Class Type: 0
Vendor ID: 1356
Product ID: 616