Core:
  PPU Decoder: Recompiler (LLVM)
  PPU Threads: 2
  PPU Debug: false
  Save LLVM logs: false
  Use LLVM CPU: ""
  Max LLVM Compile Threads: 0
  PPU LLVM Greedy Mode: false
  Enable thread scheduler: false
  Set DAZ and FTZ: false
  SPU Decoder: Recompiler (LLVM)
  Lower SPU thread priority: false
  SPU GETLLAR polling detection: false
  SPU Debug: false
  Preferred SPU Threads: 0
  SPU delay penalty: 3
  SPU loop detection: true
  Max SPURS Threads: 6
  SPU Block Size: Safe
  Accurate GETLLAR: false
  Accurate SPU DMA: false
  Accurate Cache Line Stores: false
  Accurate RSX reservation access: false
  SPU Verification: true
  SPU Cache: true
  SPU Profiler: false
  Enable TSX: Disabled
  Accurate xfloat: false
  Approximate xfloat: true
  LLVM Accurate DFMA: true
  PPU LLVM Java Mode Handling: false
  Accurate PPU 128-byte Reservation Op Max Length: 0
  PPU LLVM Accurate Vector NaN values: false
  Stub PPU Traps: 0
  Debug Console Mode: false
  Hook static functions: false
  Libraries Control:
    - liblv2.sprx:hle
  HLE lwmutex: false
  SPU LLVM Lower Bound: 0
  SPU LLVM Upper Bound: 18446744073709551615
  TSX Transaction First Limit: 800
  TSX Transaction Second Limit: 2000
  Clocks scale: 100
  Sleep Timers Accuracy: Usleep Only
  Performance Report Threshold: 500
  Enable Performance Report: false
  Accurate PUTLLUC: false
  Lib Loader: Load liblv2.sprx only
  Load libraries: []
VFS:
  $(EmulatorDir): /storage/.config/rpcs3/
  /dev_hdd0/: $(EmulatorDir)dev_hdd0/
  /dev_hdd1/: $(EmulatorDir)rpcs3/dev_hdd1/
  /dev_flash/: $(EmulatorDir)rpcs3/dev_flash/
  /dev_usb000/: $(EmulatorDir)rpcs3/dev_usb000/
  /dev_bdvd/: ""
  /app_home/: ""
  Enable /host_root/: false
  Initialize Directories: true
  Limit disk cache size: false
  Disk cache maximum size (MB): 5120
Video:
  Renderer: OpenGL
  Resolution: 1280x720
  Aspect ratio: 16:9
  Frame limit: Off
  MSAA: Auto
  Shader Mode: Async Shader Recompiler
  Write Color Buffers: false
  Write Depth Buffer: false
  Read Color Buffers: false
  Read Depth Buffer: false
  Log shader programs: false
  VSync: true
  Debug output: false
  Debug overlay: false
  Use Legacy OpenGL Buffers: false
  Use GPU texture scaling: false
  Stretch To Display Area: false
  Force High Precision Z buffer: false
  Strict Rendering Mode: false
  Disable ZCull Occlusion Queries: false
  Disable Vertex Cache: false
  Disable FIFO Reordering: false
  Enable Frame Skip: false
  Force CPU Blit: false
  Disable On-Disk Shader Cache: false
  Disable Vulkan Memory Allocator: false
  Use full RGB output range: true
  Strict Texture Flushing: false
  Disable native float16 support: false
  Multithreaded RSX: false
  Relaxed ZCULL Sync: false
  Enable 3D: false
  Debug Program Analyser: false
  Consecutive Frames To Draw: 1
  Consecutive Frames To Skip: 1
  Resolution Scale: 100
  Anisotropic Filter Override: 0
  Texture LOD Bias Addend: 0
  Minimum Scalable Dimension: 16
  Shader Compiler Threads: 0
  Driver Recovery Timeout: 1000000
  Driver Wake-Up Delay: 1
  Vblank Rate: 60
  DECR memory layout: false
  Vulkan:
    Adapter: ""
    Force FIFO present mode: false
    Force primitive restart flag: false
  Performance Overlay:
    Enabled: false
    Enable Framerate Graph: false
    Enable Frametime Graph: false
    Detail level: Medium
    Metrics update interval (ms): 350
    Font size (px): 10
    Position: Top Left
    Font: n023055ms.ttf
    Horizontal Margin (px): 50
    Vertical Margin (px): 50
    Center Horizontally: false
    Center Vertically: false
    Opacity (%): 70
    Body Color (hex): "#FFE138FF"
    Body Background (hex): "#002339FF"
    Title Color (hex): "#F26C24FF"
    Title Background (hex): "#00000000"
  Shader Compilation Hint:
    Position X (px): 20
    Position Y (px): 690
  Shader Loading Dialog:
    Allow custom background: true
    Darkening effect strength: 30
    Blur effect strength: 0
  Disable Asynchronous Shader Compiler: false
  D3D12:
    Adapter: ""
Audio:
  Renderer: OpenAL
  Dump to file: false
  Convert to 16 bit: false
  Audio Channels: Downmix to Stereo
  Start Threshold: 1
  Master Volume: 100
  Enable Buffering: true
  Desired Audio Buffer Duration: 100
  Sampling Period Multiplier: 100
  Enable Time Stretching: false
  Time Stretching Threshold: 75
  Microphone Type: "Null"
  Microphone Devices: "@@@@@@@@@@@@"
  Downmix to Stereo: true
Input/Output:
  Keyboard: "Null"
  Mouse: Basic
  Camera: "Null"
  Camera type: Unknown
  Move: "Null"
  Pad: Keyboard
System:
  License Area: SCEE
  Language: English (US)
  Keyboard Type: English keyboard (US standard)
  Enter button assignment: Enter with cross
  Console time offset (s): 0
Net:
  Internet enabled: Connected
  IP address: 192.168.1.1
  DNS address: 8.8.8.8
  IP swap list: ""
  PSN status: Disconnected
  Connection status: Disconnected
Miscellaneous:
  Automatically start games after boot: true
  Exit RPCS3 when process finishes: false
  Start games in fullscreen mode: true
  Prevent display sleep while running games: true
  Show trophy popups: true
  Show shader compilation hint: true
  Use native user interface: true
  GDB Server: 127.0.0.1:2345
  Silence All Logs: false
  Window Title Format: "FPS: %F | %R | %V | %T [%t]"
  Show FPS counter in window title: true
  Port: 2345
Log: {}
